### ISSUE TITLE
Quote handling might be off

### ISSUE THREAD

**Issue by MatthewGM** [DanMcLaughlin/antlr4#38]
After generating the VisualBasic6 files, I modified your demo program to read a file as the input and tried running the vb6 HelloWorld example through it, but it seems to choke on quoted strings (I also tried a more complex example and it similarly bombed out on a string.)
If you change "Hello World!" to Hello (no quotes, single word) and "Arial" to Arial (again, no quotes), parsing works, as seen in
[test.bas.txt](https://github.com/DanMcLaughlin/antlr4/files/440424/test.bas.txt)

Perhaps I'm just passing in the istream incorrectly?  Output below and modified demo file attached.

[main.txt](https://github.com/DanMcLaughlin/antlr4/files/440423/main.txt)

line 10:20 token recognition error at: '"H'
line 10:26 mismatched input ' ' expecting 'NEWLINE'
Parse Tree: (module (moduleBody (moduleBodyElement (subStmt (visibility Private) Sub   (ambiguousIdentifier cmdClear_Click) (argList ( )) \n     (block (block Stmt (letStmt (implicitCallStmt_InStmt (iCS_S_MembersCall (iCS_S_VariableOrProcedureCall (ambiguousIdentifier txtHello)) (iCS_S_MemberCall . (iCS_S_VariableOrProcedureCall (ambiguousIdentifier (ambiguousKeyword Text))))))   =   (valueStmt (literal ""))))) \n End Sub)) \n  \n (moduleBodyElement (subStmt (visibility Private)   Sub   (ambiguousIdentifier cmdExit_Click) (argList ( )) \n     (block (blockStmt (endStmt End))) \n End Sub)) \n  \n (moduleBodyElement (subStmt (visibility Private)   Sub   (ambiguousIdentifier cmdHello_Click) (argList ( )) \n     (block (blockStmt (letStmt (implicitCallStmt_InStmt (iCS_S_MembersCall (iCS_S_VariableOrProcedureCall (ambiguousIdentifier txtHello)) (iCS_S_MemberCall . (iCS_S_VariableOrProcedureCall (ambiguousIdentifier (ambiguousKeyword Text))))))   =(valueStmt (implicitCallStmt_InStmt (iCS_S_VariableOrProcedureCall (ambiguousIdentifier ello))))))))))  )

[Edit]:
 - This was done using the pre-built ANTLR jar on soft-gems.net and compiled with VS2013 on Windows 7
 - I also tried giving it input text directly instead of using an ifstream ('ANTLRInputStream input("txtHello.Text = \"Hello World!\"");') and got the same result.

**Comment by mike-lischke** [comment]
That sounds like a pure grammar problem and not related to the C++ runtime.

**Comment by MatthewGM** [comment]
It's not a grammar problem.  Or rather, if it is, there is a bug in the ANTLR main branch, since the grammar comes directly from the ANTLR4 grammar repository and works correctly in the Java runtime.

**Comment by mike-lischke** [comment]
@MatthewGM Can you attach a complete project that I can use to play with (grammar, project files etc.)?

**Comment by MatthewGM** [comment]
Of course.  
Attached is the project I'm using.  It is a tiny mod of the demo 
I ran 
`c:\workspace\antlr\DanMcLaughlin\antlr4\runtime\Cpp\Demo-VB6>java -jar antlr4-4.5.4-SNAPSHOT.jar -Dlanguage=Cpp -package antlrcpptest -listener -visitor -o generated VisualBasic6.g4
`
The grammar is pulled directly from the grammars repo, updated to have a token named NUL instead of NULL since NULL is reserved in CPP.  The helloworld.bas is also pulled directly from the repo.

Ran it in the following manner and got the following output
`
[Demo-VB6.zip](https://github.com/DanMcLaughlin/antlr4/files/478361/Demo-VB6.zip)

c:\workspace\antlr\DanMcLaughlin\antlr4\runtime\Cpp\Demo-VB6>"Windows\bin\vs-201
3\x86\Debug DLL\antlr4cpp-demo.exe"
line 10:20 token recognition error at: '"H'
line 10:26 mismatched input ' ' expecting 'NEWLINE'
Parse Tree: (module (moduleBody (moduleBodyElement (subStmt (visibility Private)
   Sub   (ambiguousIdentifier cmdClear_Click) (argList ( )) \n     (block (block
Stmt (letStmt (implicitCallStmt_InStmt (iCS_S_MembersCall (iCS_S_VariableOrProce
dureCall (ambiguousIdentifier txtHello)) (iCS_S_MemberCall . (iCS_S_VariableOrPr
ocedureCall (ambiguousIdentifier (ambiguousKeyword Text))))))   =   (valueStmt (
literal ""))))) \n End Sub)) \n  \n (moduleBodyElement (subStmt (visibility Priv
ate)   Sub   (ambiguousIdentifier cmdExit_Click) (argList ( )) \n     (block (bl
ockStmt (endStmt End))) \n End Sub)) \n  \n (moduleBodyElement (subStmt (visibil
ity Private)   Sub   (ambiguousIdentifier cmdHello_Click) (argList ( )) \n     (
block (blockStmt (letStmt (implicitCallStmt_InStmt (iCS_S_MembersCall (iCS_S_Var
iableOrProcedureCall (ambiguousIdentifier txtHello)) (iCS_S_MemberCall . (iCS_S_
VariableOrProcedureCall (ambiguousIdentifier (ambiguousKeyword Text))))))   =
(valueStmt (implicitCallStmt_InStmt (iCS_S_VariableOrProcedureCall (ambiguousIde
ntifier ello))))))))))  )`

**Comment by mike-lischke** [comment]
I'm sorry, but I don't know what's happening for you. I tried your demo app on both Windows and macOS and in both cases it works nicely. This is the VS 2013 output:

`(startRule (module (moduleBody (moduleBodyElement (subStmt (visibility Private)   Sub   (ambiguousIdentifier cmdClear_Click) (argList ( )) \n     (block (blockStmt (letStmt (implicitCallStmt_InStmt (iCS_S_MembersCall (iCS_S_VariableOrProcedureCall (ambiguousIdentifier txtHello)) (iCS_S_MemberCall . (iCS_S_VariableOrProcedureCall (ambiguousIdentifier (ambiguousKeyword Text))))))   =   (valueStmt (literal ""))))) \n End Sub)) \n  \n (moduleBodyElement (subStmt (visibility Private)   Sub   (ambiguousIdentifier cmdExit_Click) (argList ( )) \n     (block (blockStmt (endStmt End))) \n End Sub)) \n  \n (moduleBodyElement (subStmt (visibility Private)   Sub   (ambiguousIdentifier cmdHello_Click) (argList ( )) \n     (block (blockStmt (letStmt (implicitCallStmt_InStmt (iCS_S_MembersCall (iCS_S_VariableOrProcedureCall (ambiguousIdentifier txtHello)) (iCS_S_MemberCall . (iCS_S_VariableOrProcedureCall (ambiguousIdentifier (ambiguousKeyword Text))))))   =   (valueStmt (literal "Hello World!")))) \n     (blockStmt (withStmt
 With   (implicitCallStmt_InStmt (iCS_S_VariableOrProcedureCall (ambiguousIdentifier txtHello))) \n         (block (blockStmt (letStmt (implicitCallStmt_InStmt (iCS_S_MembersCall (iCS_S_MemberCall . (iCS_S_VariableOrProcedureCall (ambiguousIdentifier Font)))))   =   (valueStmt (literal "Arial")))) \n         (blockStmt (letStmt (implicitCallStmt_InStmt (iCS_S_MembersCall (iCS_S_MemberCall . (iCS_S_VariableOrProcedureCall (ambiguousIdentifier FontSize)))))   =   (valueStmt (literal 16)))) \n         (blockStmt (letStmt (implicitCallStmt_InStmt (iCS_S_MembersCall (iCS_S_MemberCall . (iCS_S_VariableOrProcedureCall (ambiguousIdentifier ForeColor)))))   =   (valueStmt (implicitCallStmt_InStmt (iCS_S_VariableOrProcedureCall (ambiguousIdentifier vbBlue))))))) \n     End With))) \n End Sub))) \n \n) <EOF>)`


and here XCode 8:

`(startRule (module (moduleBody (moduleBodyElement (subStmt (visibility Private)   Sub   (ambiguousIdentifier cmdClear_Click) (argList ( )) \n     (block (blockStmt (letStmt (implicitCallStmt_InStmt (iCS_S_MembersCall (iCS_S_VariableOrProcedureCall (ambiguousIdentifier txtHello)) (iCS_S_MemberCall . (iCS_S_VariableOrProcedureCall (ambiguousIdentifier (ambiguousKeyword Text))))))   =   (valueStmt (literal ""))))) \n End Sub)) \n  \n (moduleBodyElement (subStmt (visibility Private)   Sub   (ambiguousIdentifier cmdExit_Click) (argList ( )) \n     (block (blockStmt (endStmt End))) \n End Sub)) \n  \n (moduleBodyElement (subStmt (visibility Private)   Sub   (ambiguousIdentifier cmdHello_Click) (argList ( )) \n     (block (blockStmt (letStmt (implicitCallStmt_InStmt (iCS_S_MembersCall (iCS_S_VariableOrProcedureCall (ambiguousIdentifier txtHello)) (iCS_S_MemberCall . (iCS_S_VariableOrProcedureCall (ambiguousIdentifier (ambiguousKeyword Text))))))   =   (valueStmt (literal "Hello World!")))) \n     (blockStmt (withStmt With   (implicitCallStmt_InStmt (iCS_S_VariableOrProcedureCall (ambiguousIdentifier txtHello))) \n         (block (blockStmt (letStmt (implicitCallStmt_InStmt (iCS_S_MembersCall (iCS_S_MemberCall . (iCS_S_VariableOrProcedureCall (ambiguousIdentifier Font)))))   =   (valueStmt (literal "Arial")))) \n         (blockStmt (letStmt (implicitCallStmt_InStmt (iCS_S_MembersCall (iCS_S_MemberCall . (iCS_S_VariableOrProcedureCall (ambiguousIdentifier FontSize)))))   =   (valueStmt (literal 16)))) \n         (blockStmt (letStmt (implicitCallStmt_InStmt (iCS_S_MembersCall (iCS_S_MemberCall . (iCS_S_VariableOrProcedureCall (ambiguousIdentifier ForeColor)))))   =   (valueStmt (implicitCallStmt_InStmt (iCS_S_VariableOrProcedureCall (ambiguousIdentifier vbBlue))))))) \n     End With))) \n End Sub))) \n \n) <EOF>)
Program ended with exit code: 0`

A few notes: your demo doesn't work as is, because the grammar cannot be loaded without specifying the correct path to it. The grammar uses a weird encoding, it's not utf-8 (as it should be). You can see that with the äÄöÖüÜ characters for the LETTER and LETTERORDIGIT fragment rules. I didn't fix the grammar, but the path to it in the demo app and everything works nicely for me. Not sure what to do here.

**Comment by mike-lischke** [comment]
Note: I used the current git repo for the C++ runtime (i.e. I copied your VB demo into the antlr4/runtime/Cpp/ folder and ran it from there). Check with the latest git source, just in case.

**Comment by mike-lischke** [comment]
I reworked the handling of signed token values which could have cause trouble with signed -> unsigned conversion e.g. under 32bit. Please test the latest git head to see if you problem is solved by that.

**Comment by mike-lischke** [comment]
I guess, no message is a good message, so I'm closing this issue as solved.
